### PR TITLE
Added updateMask Parameter to updateDocument_

### PR DESCRIPTION
**Pull request by webstermath**
Loops through the keys in the `fields` variable and adds them to the parameters with `request.addParam('updateMask.fieldPaths',field)`

In response to issue #23: Allow updateMask to be set for Patch/Updating documents

### CODE REVIEW

**Comment by grahamearley** [comment]
I asked a design question in issue #23 about how to handle the case where we pass in an empty object to the update function — depending on where that discussion goes, this PR may need some more changes.

Until then, could you update your change to use the same spacing conventions we have throughout the codebase? Like this:
```javascript
for (field in fields) {
    request.addParam('updateMask.fieldPaths', field)
}
```

**Comment by webstermath** [comment]
Does that look good?

**Comment by grahamearley** [comment]
Yep, thanks! I'm going to wait to approve this PR until we figure out how to handle the `{}` case I asked about in issue #23.

**Comment by grahamearley** [comment]
I updated the issue with [a comment](https://github.com/grahamearley/FirestoreGoogleAppsScript/issues/23#issuecomment-419732016) suggesting how to handle the case where an empty object is passed in. What do you think? Could you make these changes to this PR?

**Pull request closed without merging**
