### PR TITLE
Added query support and ability to get all documents from a collection

### PR DESCRIPTION
**Pull request by thesandlord**
Please test and let me know what needs to be changed!

### CODE REVIEW

**Comment by grahamearley** [comment]
Hey @thesandlord, have you been able to run queries successfully with this? I'm having some trouble. Here are the issues I'm having:

### Queries with a collection path not at the root level
In the [Structured Query](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/StructuredQuery#Order) documentation, the `"from"` field is a [`CollectionSelector`](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/StructuredQuery#CollectionSelector), which has a `"collectionId"` field. This field's description is:

> The collection ID. When set, selects only collections with this ID. 

When making a `StructuredQuery` to pass into your `query(...)` function, I get an error when I put slashes in this `"collectionId"` field because it's meant to be strictly the name of the collection, not a path to a collection. That's where the `"allDescendants"` field comes in handy. If you set it to `true`, it will look for any collections with the given name that are children of the collection you're running the query in.

Currently, we're running the query in the root collection. This is specified in the [`baseUrl` variable in the `_query(...)` function](https://github.com/grahamearley/FirestoreGoogleAppsScript/pull/6/files#diff-b8a3235fcaa8249c9e823d6e94bb5c68R34). To specify a collection to run the query in, we could instead set `baseUrl` like this:

```javascript
var collectionPath = "path/to/collection"
var baseUrl = "https://firestore.googleapis.com/v1beta1/projects/" + projectId + "/databases/(default)/documents/" + collectionPath + ":runQuery";
```

and we could have `collectionPath` be a parameter that the function caller passes in.

Since the `"collectionId"` field doesn't support paths, the [`getAllDocuments(path, ...)`](https://github.com/grahamearley/FirestoreGoogleAppsScript/pull/6/files#diff-b8a3235fcaa8249c9e823d6e94bb5c68R24) function doesn't work for getting all documents from a subcollection because the `path` parameter [is set as the `"collectionId"` field](https://github.com/grahamearley/FirestoreGoogleAppsScript/pull/6/files#diff-b8a3235fcaa8249c9e823d6e94bb5c68R26) for the `CollectionSelector` in the `from` field.

### Indices
I don't think this issue is explicitly related to the library, but it's giving me trouble with testing queries that don't just involve getting all the documents in a collection. Going to write it up here and see if anyone has any thoughts on what's going on (I could be doing something wrong!).

Whenever I make a query with a `Filter` in the `"where"` field, the HTTP response tells me I need to make an index and it provides me with a URL to make that index. This is expected.

However, even when I create the index, it doesn't seem to do anything. The HTTP response *still* tells me to create an index and gives me a URL to do so, and when I go to this URL, Firestore tells me that the index already exists and that I don't need to do anything. 

Additionally, if I make a query that filters only on a single field, the response tells me to create an index and gives me a URL. But when I go to the URL and click "Create index," I see a message that says

> this index is not necessary, single field indexes are built in

So I can't run my query without the index, and Firestore tells me I don't need the index (and I know that I don't need the index because I've run single field queries before with no problem from other clients).

Here's the structured query I'm running to get this behavior:

```javascript
function testQuery() {
  var structuredQuery = {
    from: [
      {
        collectionId: "children",
        allDescendants: true
      }
    ],
    
    where: {
      unaryFilter: {
        op: "IS_NULL",
        field: {
          fieldPath: "parent"
        }
      }
    }
  }
  
  var response = query(structuredQuery, email, key, projectId);
  Logger.log(response);  
}
```

This query is looking for documents in the `children` collection whose `parent` field is null. The response tells me to make an index, but Firestore won't let me create that index (and it shouldn't have to).

***

What do you think? Am I missing something or are you also getting these behaviors?

Aside from these things, it looks nice! Thanks for contributing this!

**Comment by thesandlord** [comment]
Yeah, looks like we need the path as another parameter. I think for getAllDocuments we can implicitly parse the path and collection from the path parameter. I'll add the code.

I don't know about the indices unfortunately, I just got really busy and haven't had a chance to look at it.

**Comment by grahamearley** [comment]
Hey @thesandlord, any updates on this PR? I know you said you're busy :) If it helps, I might be able to update the `getAllDocuments` method to implicitly parse the path and collection and get this update pulled in.

**Comment by grahamearley** [comment]
I merged #10 in, and it changed the way this library works — now there is a `Firestore` object that gets authenticated upon construction, and then can make calls to Firestore without having to authenticate each time. This means that this PR will need some updates so that the query methods are available through the `Firestore` object.

@thesandlord Do you have the time to update this PR? Are you okay with me doing it (and giving you credit)?

**Comment by grahamearley** [comment]
I tried testing the query functionality again with another project, and still couldn't get it to work. The HTTP response tells me to set up an index (even for single-field queries, where you don't need an index). When I set up the index, the response *still* tells me to do set up the index.

Here's another test query, with multiple fields.
```javascript
function testNameQuery() {
  var nameQuery = {
    select: {
      fields: []
    },
    
    from: [
      {
        collectionId: "children",
        allDescendants: true
      }
    ],
    
    where: {
      fieldFilter: {
        op: "EQUAL",
        field: {
          fieldPath: "name"
        },
        value: {
          "stringValue": "test",
        }
      }
    },
    
    orderBy: {
      field: {
          fieldPath: "num"
      },
      direction: "ASCENDING"
    },
    
    offset: 0,
    limit: 60
  }
  
  var response = query(nameQuery, email, key, projectId);
  Logger.log(response);  
}
```

@thesandlord / anyone else — can you test this and see if you get the same behavior?

**Comment by grahamearley** [comment]
@LaughDonor Awesome! Thanks for checking on this. I wonder if it's a bug with Firestore's REST API. Looking forward to the PR!

**Comment by grahamearley** [comment]
I'm gonna close this PR now that #26 is merged in.

**Pull request closed without merging**
